language: php
php:
- 5.3.3
- 5.3
- 5.4
- 5.5
- 5.6
- hhvm
matrix:
allow_failures:
- php: hhvm
before_script:
- composer self-update
- composer install
- composer require --dev --no-update phpunit/phpunit:@stable phpunit/php-code-coverage:@dev satooshi/php-coveralls:@dev
- composer update phpunit/php-code-coverage satooshi/php-coveralls
- mkdir -p ./build/logs
script:
- ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
after_script:
- 'echo ''src_dir: .'' >> ./.coveralls.yml'
- php ./vendor/bin/coveralls -v
notifications:
email: false